// Generated by CoffeeScript 1.10.0

/*
  游戏主界面
 */

(function() {
  var MainLayer;

  MainLayer = LayerBase.extend({
    mScrollView: null,
    mBtnSettings: null,
    mLastOpenLevel: 1,
    mMenuLayerHeight: 140,
    mMenuLayer: null,
    mBtnExit: null,
    ctor: function() {
      this._super();
      this.mCurLevel = DataUtil.getDataItem(Keys.CURRENT_LEVEL, 0);
      if (this.mCurLevel <= 0) {
        this.mCurLevel = 1;
      }
      this.addMenuLayer();
      this.addBtnFriend();
      this.addBtnSettings();
      this.addBtnExitGame();
      return this.initScrollView();
    },
    addMenuLayer: function() {
      this.mMenuLayer = new cc.LayerColor(cc.color(168, 132, 174, 255));
      this.mMenuLayer.ignoreAnchorPointForPosition(false);
      this.mMenuLayer.attr({
        width: cc.winSize.width,
        height: this.mMenuLayerHeight,
        anchorX: 0.5,
        anchorY: 0,
        x: cc.winSize.width / 2,
        y: 0
      });
      this.addChild(this.mMenuLayer, 5);
      return TouchUtil.onClick(this.mMenuLayer, function() {
        return false;
      });
    },
    addBtnSettings: function() {
      var btn, self;
      btn = new ccui.Button();
      btn.loadTextureNormal(resImg.settings, ccui.Widget.LOCAL_TEXTURE);
      btn.setPressedActionEnabled(true);
      btn.setTouchEnabled(true);
      btn.attr({
        anchorX: 0,
        anchorY: 0.5,
        x: 50,
        y: this.mMenuLayer.height / 2
      });
      this.mMenuLayer.addChild(btn, 5);
      self = this;
      return btn.addTouchEventListener(function(touch, event) {
        var settingsDialog;
        if (event === ccui.Widget.TOUCH_ENDED) {
          AudioManager.playClickAudio();
          jlog.i("设置按钮点击回调");
          settingsDialog = new SettingsDialog();
          self.addChild(settingsDialog, 2000);
          return jlog.i("settingsDialog   =  " + settingsDialog.getLocalZOrder());
        }
      }, btn);
    },
    addBtnFriend: function() {
      var btn;
      btn = new ccui.Button();
      btn.loadTextureNormal(resImg.friend, ccui.Widget.LOCAL_TEXTURE);
      btn.setPressedActionEnabled(true);
      btn.setTouchEnabled(true);
      btn.attr({
        anchorX: 0.5,
        anchorY: 0.5,
        x: this.mMenuLayer.width / 2,
        y: this.mMenuLayer.height / 2
      });
      this.mMenuLayer.addChild(btn, 5);
      return btn.addTouchEventListener(function(touch, event) {
        if (event === ccui.Widget.TOUCH_ENDED) {
          AudioManager.playClickAudio();
          jlog.i("QQ登录");
          if (ccUtil.isAndroid()) {
            jsb.reflection.callStaticMethod(Configs.mAndroidPackageName + "/YSDKHelper", "loginQQ", "()V");
            return jsb.reflection.callStaticMethod(Configs.mAndroidPackageName + "/YSDKHelper", "queryUserInfo", "()V");
          }
        }
      }, btn);
    },
    addBtnExitGame: function() {
      var btn, self;
      btn = new ccui.Button();
      btn.loadTextureNormal(resImg.exit_game, ccui.Widget.LOCAL_TEXTURE);
      btn.setPressedActionEnabled(true);
      btn.setTouchEnabled(true);
      btn.attr({
        anchorX: 1.0,
        anchorY: 0.5,
        x: this.mMenuLayer.width - 50,
        y: this.mMenuLayer.height / 2
      });
      this.mMenuLayer.addChild(btn, 5);
      self = this;
      return btn.addTouchEventListener(function(touch, event) {
        var confirm;
        if (event === ccui.Widget.TOUCH_ENDED) {
          AudioManager.playClickAudio();
          confirm = new ConfirmExitDialog();
          self.addChild(confirm, 20);
          return DataUtil.saveData();
        }
      }, btn);
    },
    initScrollView: function() {
      var bigLevels, curBigLevel, i, j, layer, percent, ref, results, self, size;
      self = this;
      this.mScrollView = new ccui.ScrollView();
      this.mScrollView.setDirection(ccui.ScrollView.DIR_VERTICAL);
      if (ccUtil.isNative()) {
        this.mScrollView.setScrollBarEnabled(false);
      }
      this.mScrollView.setInertiaScrollEnabled(true);
      this.mScrollView.setTouchEnabled(true);
      this.mScrollView.setContentSize(cc.size(cc.winSize.width, cc.winSize.height - this.mMenuLayerHeight));
      this.mScrollView.setInnerContainerSize(cc.size(cc.winSize.width, 256 * 5));
      this.mScrollView.attr({
        anchorX: 0.5,
        anchorY: 1,
        x: cc.winSize.width / 2,
        y: cc.winSize.height
      });
      percent = 100 - this.mCurLevel / 50 * 100;
      this.mScrollView.scrollToPercentVertical(percent, 0.5, false);
      this.addChild(this.mScrollView, 0);
      bigLevels = Configs.mSettings[Keys.LEVELS];
      curBigLevel = Math.floor(this.mCurLevel / 5);
      jlog.i("CurBigLevel = " + curBigLevel + "    @mCurLevel = " + this.mCurLevel);
      size = this.mScrollView.getContentSize();
      results = [];
      for (i = j = 0, ref = bigLevels.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        if (i > curBigLevel) {
          layer = new LevelLayer(bigLevels[i].colors[0], i, true);
        } else {
          layer = new LevelLayer(bigLevels[i].colors[0], i, false);
        }
        layer.ignoreAnchorPointForPosition(false);
        layer.attr({
          width: cc.winSize.width,
          height: 256,
          x: cc.winSize.width / 2,
          y: 256 * (i + 0.5)
        });
        results.push(this.mScrollView.addChild(layer, 0));
      }
      return results;
    },
    getColor: function(level) {
      var bigLevel, color, index, sLevel;
      level = level - 1;
      bigLevel = Math.floor(level / 10);
      sLevel = level % 10;
      index = sLevel % 5 + 1;
      color = Configs.mSettings[Keys.LEVELS][bigLevel][Keys.COLORS][index];
      return color;
    }
  });

  this.MainScene1 = cc.Scene.extend({
    onEnter: function() {
      var layer;
      this._super();
      layer = new MainLayer();
      return this.addChild(layer);
    }
  });

}).call(this);

//# sourceMappingURL=MainScene1.js.map
