// Generated by CoffeeScript 1.10.0

/*
  游戏控制类
 */

(function() {
  this.GameController = cc.Class.extend({
    mCurScene: null,
    mGameState: null,
    mIsNewGame: true,
    mCurLevel: null,
    mSelectLevel: null,
    init: function() {
      return true;
    },
    setCurScene: function(s) {
      if (this.mCurScene !== s) {
        if (this.mCurScene !== null) {
          this.mCurScene.onExit();
        }
      }
      this.mCurScene = s;
      if (this.mCurScene) {
        this.mCurScene.onEnter();
        return cc.director.runScene(s);
      }
    },
    getCurScene: function() {
      return this.mCurScene;
    },
    runGame: function() {
      return jlog.i("run game");
    },
    newGame: function() {
      return jlog.i("new game");
    },
    option: function() {
      return jlog.i("option");
    },
    about: function() {
      return jlog.i("about");
    }
  });

  this.GameController.getInstance = function() {
    cc.assert(this._sharedGame, "Havn't call setSharedGame");
    if (!this._sharedGame) {
      this._sharedGame = new GameController();
      if (this._sharedGame.init()) {
        return this._sharedGame;
      }
    } else {
      return this._sharedGame;
    }
    return null;
  };

  this.GameController._sharedGame = null;

}).call(this);

//# sourceMappingURL=GameController.js.map
