// Generated by CoffeeScript 1.10.0

/*
  确认退出对话框
 */

(function() {
  this.ConfirmExitDialog = PopLayerBase.extend({
    mBgLayer: null,
    mBtnClose: null,
    mCloseCallback: null,
    ctor: function() {
      this._super();
      this.setTouchbgHide(false);
      this.addBgLayer();
      this.addCloseBtn();
      this.addTip();
      this.addBtnConfirm();
      return this.addBtnBack();
    },
    addBgLayer: function() {
      this.mBgLayer = new cc.LayerColor(cc.color(255, 255, 255, 255));
      this.mBgLayer.ignoreAnchorPointForPosition(false);
      this.mBgLayer.setContentSize(400, 300);
      this.mBgLayer.attr({
        x: cc.winSize.width / 2,
        y: cc.winSize.height / 2
      });
      this.addChild(this.mBgLayer);
      return TouchUtil.cannotClick(this.mBgLayer);
    },
    addCloseBtn: function() {
      var self;
      this.mBtnClose = new ccui.Button();
      this.mBtnClose.loadTextureNormal(resImg.close, ccui.Widget.LOCAL_TEXTURE);
      this.mBtnClose.setPressedActionEnabled(true);
      this.mBtnClose.attr({
        x: this.mBgLayer.width - 30,
        y: this.mBgLayer.height - 30
      });
      this.mBtnClose.setTouchEnabled(true);
      this.mBgLayer.addChild(this.mBtnClose, 5);
      self = this;
      return this.mBtnClose.addTouchEventListener(function(touch, event) {
        if (event === ccui.Widget.TOUCH_ENDED) {
          return self.hidden(self.mCloseCallback);
        }
      }, this.mBtnClose);
    },
    addTip: function() {
      var label;
      label = new cc.LabelTTF("您确定要退出游戏？");
      label.attr({
        fontSize: 30,
        fillStyle: cc.color(0, 0, 0, 255),
        x: this.mBgLayer.width / 2,
        y: this.mBgLayer.height / 2 + 50
      });
      return this.mBgLayer.addChild(label);
    },
    addBtnConfirm: function() {
      var btn, param;
      param = {
        normal: cc.color(52, 155, 255, 120),
        title: "确定",
        size: cc.p(120, 60),
        fontSize: 35,
        callback: function() {
          return cc.director.end();
        }
      };
      btn = new PureColorButton(param);
      btn.attr({
        anchorX: 0,
        anchorY: 0.5,
        x: 50,
        y: 60
      });
      return this.mBgLayer.addChild(btn, 5);
    },
    addBtnBack: function() {
      var btn, param, self;
      self = this;
      param = {
        normal: cc.color(52, 155, 255, 255),
        title: "返回",
        size: cc.p(120, 60),
        fontSize: 35,
        callback: function() {
          return self.hidden(self.mCloseCallback);
        }
      };
      btn = new PureColorButton(param);
      btn.attr({
        anchorX: 1,
        anchorY: 0.5,
        x: this.mBgLayer.width - 50,
        y: 60
      });
      return this.mBgLayer.addChild(btn, 5);
    },
    setHiddenCallback: function(fun) {
      return this.mCloseCallback = fun;
    }
  });

}).call(this);

//# sourceMappingURL=ConfirmExitDialog.js.map
