// Generated by CoffeeScript 1.10.0

/*
  游戏结束对话框
 */

(function() {
  this.GameOverDialog = PopLayerBase.extend({
    mBtnLayer: null,
    mBtn: null,
    mBtnClose: null,
    mCloseCallback: null,
    mBtnCallBack: null,
    ctor: function(img, title) {
      this._super();
      this.setTouchbgHide(false);
      this.addBgLayer();
      this.addImg(img);
      this.addBtnLayer();
      this.addCloseBtn();
      this.addBtn(title);
      return this.show();
    },
    addBgLayer: function() {
      this.mBgLayer = new cc.Layer();
      this.mBgLayer.ignoreAnchorPointForPosition(false);
      this.mBgLayer.setContentSize(400, 300);
      this.mBgLayer.attr({
        x: cc.winSize.width / 2,
        y: cc.winSize.height / 2
      });
      return this.addChild(this.mBgLayer);
    },
    addImg: function(img) {
      var sprite;
      sprite = new cc.Sprite(img);
      sprite.attr({
        anchorX: 0.5,
        anchorY: 1,
        x: this.mBgLayer.width / 2,
        y: this.mBgLayer.height
      });
      return this.mBgLayer.addChild(sprite, 0);
    },
    addBtnLayer: function() {
      this.mBtnLayer = new cc.LayerColor(cc.color(255, 255, 255, 255), 400, 140);
      this.mBtnLayer.ignoreAnchorPointForPosition(false);
      this.mBtnLayer.attr({
        anchorX: 0.5,
        anchorY: 0,
        x: this.mBgLayer.width / 2,
        y: 0
      });
      this.mBgLayer.addChild(this.mBtnLayer, 0);
      this.mPopDialog = new PopLayerBase(this.mBgLayer, true, true);
      return this.addChild(this.mPopDialog);
    },
    addCloseBtn: function() {
      var self;
      this.mBtnClose = new ccui.Button();
      this.mBtnClose.loadTextureNormal(resImg.close, ccui.Widget.LOCAL_TEXTURE);
      this.mBtnClose.setPressedActionEnabled(true);
      this.mBtnClose.attr({
        anchorX: 1,
        anchorY: 1,
        x: this.mBtnLayer.width - 15,
        y: this.mBtnLayer.height - 15
      });
      this.mBtnClose.setTouchEnabled(true);
      this.mBtnLayer.addChild(this.mBtnClose, 5);
      self = this;
      return this.mBtnClose.addTouchEventListener(function(touch, event) {
        if (event === ccui.Widget.TOUCH_ENDED) {
          return self.hidden(self.mCloseCallback);
        }
      }, this.mBtnClose);
    },
    addBtn: function(title) {
      var param, self;
      param = {
        "title": title
      };
      this.mBtn = new PureColorButton(param);
      self = this;
      this.mBtn.setCallBack(function() {
        return self.hidden(self.mBtnCallBack);
      });
      this.mBtn.attr({
        anchorX: 0.5,
        anchorY: 0.5,
        x: this.mBtnLayer.width / 2,
        y: this.mBtnLayer.height / 2
      });
      return this.mBtnLayer.addChild(this.mBtn, 0);
    },
    setHiddenCallback: function(fun) {
      return this.mCloseCallback = fun;
    },
    setBtnCallback: function(cb) {
      return this.mBtnCallBack = cb;
    }
  });

}).call(this);

//# sourceMappingURL=GameOverDialog.js.map
