// Generated by CoffeeScript 1.10.0

/*
  遮罩层
 */

(function() {
  this.MarkLayer = cc.LayerColor.extend({
    ctor: function(color) {
      this._super(color);
      return this.onListener();
    },
    onListener: function() {
      var listener, self;
      self = this;
      listener = cc.EventListener.create({
        event: cc.EventListener.TOUCH_ONE_BY_ONE,
        swallowTouches: true,
        onTouchBegan: function(touch, event) {
          return true;
        },
        onTouchEnded: function(touch, event) {}
      });
      return cc.eventManager.addListener(listener, this);
    }
  });

}).call(this);

//# sourceMappingURL=MarkLayer.js.map
