// Generated by CoffeeScript 1.10.0

/*
  暂停对话框
 */

(function() {
  this.PauseDialog = PopLayerBase.extend({
    mBtnReplay: null,
    mBtnBackward: null,
    mCloseCallback: null,
    mReplayCb: null,
    ctor: function() {
      this._super();
      this.addBtnLayer();
      this.addReplayBtn();
      this.addExitGameBtn();
      this.markLayer();
      return this.show();
    },
    addBtnLayer: function() {
      this.mBgLayer = new cc.LayerColor(cc.color(255, 255, 255, 255), 400, 150);
      this.mBgLayer.ignoreAnchorPointForPosition(false);
      this.mBgLayer.attr({
        anchorX: 0.5,
        anchorY: 0.5,
        x: cc.winSize.width / 2,
        y: cc.winSize.height / 2
      });
      return this.addChild(this.mBgLayer, 0);
    },
    addReplayBtn: function() {
      var self;
      this.mBtnReplay = new ccui.Button();
      this.mBtnReplay.loadTextureNormal(resImg.replay, ccui.Widget.LOCAL_TEXTURE);
      this.mBtnReplay.setPressedActionEnabled(true);
      this.mBtnReplay.attr({
        anchorX: 1,
        x: this.mBgLayer.width / 3,
        y: this.mBgLayer.height / 2
      });
      this.mBtnReplay.setTouchEnabled(true);
      this.mBgLayer.addChild(this.mBtnReplay, 50);
      self = this;
      return this.mBtnReplay.addTouchEventListener(function(touch, event) {
        if (event === ccui.Widget.TOUCH_ENDED) {
          jlog.i("点击重玩按钮");
          self.mReplayCb();
          return self.hidden();
        }
      }, this.mBtnReplay);
    },
    addExitGameBtn: function() {
      var self;
      this.mBtnBackward = new ccui.Button();
      this.mBtnBackward.loadTextureNormal(resImg.backward, ccui.Widget.LOCAL_TEXTURE);
      this.mBtnBackward.setPressedActionEnabled(true);
      this.mBtnBackward.attr({
        anchorX: 0,
        x: this.mBgLayer.width / 3 * 2,
        y: this.mBgLayer.height / 2
      });
      this.mBtnBackward.setTouchEnabled(true);
      this.mBgLayer.addChild(this.mBtnBackward, 50);
      self = this;
      return this.mBtnBackward.addTouchEventListener(function(touch, event) {
        if (event === ccui.Widget.TOUCH_ENDED) {
          return cc.director.runScene(new MainScene());
        }
      }, this.mBtnBackward);
    },
    setReplayCb: function(fun) {
      return this.mReplayCb = fun;
    }
  });

}).call(this);

//# sourceMappingURL=PauseDialog.js.map
