// Generated by CoffeeScript 1.10.0

/*
  数据持久化key的常量键值
 */

(function() {
  this.Keys = {
    staticClass: true,
    TEA_KEY: "<;d#@r%u?m*g$e,>",
    BMOB_APPLICATION_ID: "f2b224c5e8af32ec69a6539916b56f0f",
    BMOB_REST_API_KEY: "30a6e18d0073f8fc84bf00064adda06f",
    LEVELS: "levels",
    COLORS: "colors",
    GOAL_SUM: "goal_sum",
    GOAL_SCORE: "goal_score",
    LIMIT_STEP: "limit_step",
    LIMIT_TIME: "limit_time",
    SUM_FORMULA: "sum_formula",
    STEP_FORMULA: "step_formula",
    TIME_FORMULA: "time_formula",
    SCORE_FORMULA: "scroce_formula",
    USER_ID: "user_id",
    DATA: "",
    CHANNEL_ID: "channel_id",
    MUSIC: "music",
    SOUND: "sound",
    LEVEL_HIGHEST_SCORE: "level_highest_score",
    CURRENT_LEVEL: "current_level",
    MAGIC_WAND: 0,
    BACK_ONE_STEP: 1,
    INCREASE_5_STEP: 2
  };

}).call(this);

//# sourceMappingURL=Keys.js.map
