// Generated by CoffeeScript 1.10.0

/*
  定义的一些开关变量标志
 */

(function() {
  this.OnOff = {
    staticClass: true,
    isDebug: false,
    isLogOpen: false
  };

}).call(this);

//# sourceMappingURL=OnOff.js.map
