// Generated by CoffeeScript 1.10.0

/*
  封装Cocos API以方便调用
 */

(function() {
  this.ccUtil = {
    callFunc: function(cbFunc, msg) {
      if (msg == null) {
        msg = "";
      }
      if (typeof cbFunc !== "undefined" && typeof cbFunc === "function") {
        return new cc.CallFunc(cbFunc);
      } else {
        return new cc.CallFunc(function() {
          return jlog.t(msg + " callback function is undefine or not a function ");
        });
      }
    },
    isAndroid: function() {
      return cc.sys.os === cc.sys.OS_ANDROID;
    },
    isIOS: function() {
      return cc.sys.os === cc.sys.OS_IOS;
    },
    isNative: function() {
      return cc.sys.isNative;
    },
    isMobile: function() {
      return cc.sys.isMobile;
    },
    isFunction: function(func) {
      if (typeof func !== void 0 && typeof func === "function") {
        return true;
      } else {
        jlog.t("function is undefine or not a function ");
        return false;
      }
    },
    isObjectNotNull: function(obj) {
      if ((obj !== null) && (obj !== void 0)) {
        return true;
      } else {
        return false;
      }
    }
  };

}).call(this);

//# sourceMappingURL=CcUtil.js.map
