// Generated by CoffeeScript 1.10.0

/*
  打印log日志工具类
 */

(function() {
  this.jlog = {
    staticClass: true,
    TAG_ERROR: "cocos-error",
    TAG_WARM: "cocos-warn",
    TAG_INFO: "cocos-info",
    TAG_DEBUG: "cocos-debug",
    TAG_VERBOSE: "cocos-verbose",
    TAG_THROW: "cocos-throw",
    e: function(logMsg) {
      if (OnOff.isLogOpen) {
        logMsg = StringUtil.toString(logMsg);
        return cc.log(this.TAG_ERROR + "  :  " + logMsg);
      }
    },
    w: function(logMsg) {
      if (OnOff.isLogOpen) {
        logMsg = StringUtil.toString(logMsg);
        return cc.log(this.TAG_WARM + "  :  " + logMsg);
      }
    },
    i: function(logMsg) {
      if (OnOff.isLogOpen) {
        logMsg = StringUtil.toString(logMsg);
        return cc.log(this.TAG_INFO + "  :  " + logMsg);
      }
    },
    d: function(logMsg) {
      if (OnOff.isLogOpen) {
        logMsg = StringUtil.toString(logMsg);
        return cc.log(this.TAG_DEBUG + "  :  " + logMsg);
      }
    },
    v: function(logMsg) {
      if (OnOff.isLogOpen) {
        logMsg = StringUtil.toString(logMsg);
        return cc.log(this.TAG_VERBOSE + "  :  " + logMsg);
      }
    },
    t: function(logMsg) {
      if (OnOff.isLogOpen) {
        logMsg = StringUtil.toString(logMsg);
        return cc.log(this.TAG_THROW + "  :  " + logMsg);
      }
    },
    c: function(tag, logMsg) {
      if (OnOff.isLogOpen) {
        logMsg = StringUtil.toString(logMsg);
        return cc.log(tag + "  :  " + logMsg);
      }
    },
    cc: function(logMsg) {
      if (OnOff.isLogOpen) {
        return cc.log(logMsg);
      }
    }
  };

}).call(this);

//# sourceMappingURL=LogUtil.js.map
