// Generated by CoffeeScript 1.10.0

/*
  处理字符串
 */

(function() {
  this.StringUtil = {
    toString: function(object) {
      var error, str;
      str = "";
      try {
        return str = JSON.stringify(object);
      } catch (error) {
        return str = "Object[Object]";
      } finally {
        return str;
      }
    },
    isEmpty: function(str) {
      if ((str !== null) && (str !== void 0) && (str !== "")) {
        return false;
      } else {
        return true;
      }
    },
    isString: function(json) {
      return Object.prototype.toString.call(json) === "[object String]";
    }
  };

}).call(this);

//# sourceMappingURL=StringUtil.js.map
