// Generated by CoffeeScript 1.10.0

/*
  友盟游戏数据统计帮助类
 */

(function() {
  this.UmengHelper = {
    help: function() {
      return jlog.i("pass");
    }
  };

}).call(this);

//# sourceMappingURL=UmengHelper.js.map
